server:
  port: 8081 # Your port

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hms_db
    username: postgres
    password: "admin" # Your passowrd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Set schema when app run (for dev change depending on your need)
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
